version: '3'

services:
  postgres:
    image: 'postgres:16'
    container_name: 'postgres_container'
    ports:
      - 5433:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_DB=DB4PetProject1'