spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DB4PetProject1
    username: USERNAME
    password: PASSWORD
    oracleucp:
      port-number: 5433

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      format_sql: true


  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 6000

  docker:
    compose:
      services:
        - db
        - redis
      enabled: true
