spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DB4PetProject1
    username: USERNAME
    password: PASSWORD

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      format_sql: true
